/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab7_danielalvarado;

import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author dalva
 */
public class PrincipalFrame extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalFrame
     */
    public PrincipalFrame() {
        initComponents();

        h1 = new HiloTabla1(jt_Tabla1, jp_Barra1);
        h1.start();

        h2 = new HiloTabla2(jt_Tabla2, jp_Barra2);
        h2.start();

        h3 = new HiloTabla3(jt_Tabla3, jp_Barra3);
        h3.start();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_CrearCliente = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jt_NombreC = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jt_Apellido = new javax.swing.JTextField();
        js_Edad = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jt_NumPlaca = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cb_Size = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        js_Suciedad = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        js_NumPuertas = new javax.swing.JSpinner();
        jb_CrearCliente = new javax.swing.JButton();
        jd_CrearEmpleado = new javax.swing.JDialog();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jt_NombreE = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jt_ApelldioEmpleado = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        js_EdadE = new javax.swing.JSpinner();
        jb_CrearEmpleado = new javax.swing.JButton();
        jd_VisualizarClientes = new javax.swing.JDialog();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jl_Clientes = new javax.swing.JList<>();
        jd_AgregarCarros = new javax.swing.JDialog();
        jLabel16 = new javax.swing.JLabel();
        cb_Client = new javax.swing.JComboBox<>();
        jb_Asignar = new javax.swing.JButton();
        cb_Empleados = new javax.swing.JComboBox<>();
        popup_VC = new javax.swing.JPopupMenu();
        jmi_AgregarUnCarro = new javax.swing.JMenuItem();
        jd_AgregarCarro = new javax.swing.JDialog();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jt_PlacaA = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        cb_SizeA = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        js_NumA = new javax.swing.JSpinner();
        jLabel21 = new javax.swing.JLabel();
        js_SuciedadA = new javax.swing.JSpinner();
        jb_AgregarO = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_Tabla1 = new javax.swing.JTable();
        cb_Empleado1 = new javax.swing.JComboBox<>();
        jp_Barra1 = new javax.swing.JProgressBar();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt_Tabla2 = new javax.swing.JTable();
        cb_Empleado2 = new javax.swing.JComboBox<>();
        jp_Barra2 = new javax.swing.JProgressBar();
        jScrollPane3 = new javax.swing.JScrollPane();
        jt_Tabla3 = new javax.swing.JTable();
        cb_Empleado3 = new javax.swing.JComboBox<>();
        jp_Barra3 = new javax.swing.JProgressBar();
        jb_IniciarHilos = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jm_MenuSuperior = new javax.swing.JMenu();
        jmi_CrearCliente = new javax.swing.JMenuItem();
        jmi_CrearEmpleado = new javax.swing.JMenuItem();
        jmi_VerClientes = new javax.swing.JMenuItem();
        jmi_AsignarCarros = new javax.swing.JMenuItem();
        jmi_GuardarDatos = new javax.swing.JMenuItem();
        jmi_SubirData = new javax.swing.JMenuItem();

        jd_CrearCliente.setTitle("Crear Cliente");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Crear Cliente");

        jLabel3.setText("Nombre:");

        jLabel4.setText("Apellido: ");

        js_Edad.setModel(new javax.swing.SpinnerNumberModel(18, 18, 100, 1));

        jLabel5.setText("Edad:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Crear Carro");

        jLabel7.setText("Num Placa: ");

        jLabel8.setText("Size:");

        cb_Size.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Peque", "Mediano", "Grande", " " }));

        jLabel9.setText("Niv Suciedad:");

        js_Suciedad.setModel(new javax.swing.SpinnerNumberModel(5, 5, 10, 1));

        jLabel10.setText("Num Puertas:");

        js_NumPuertas.setModel(new javax.swing.SpinnerNumberModel(2, 2, 10, 1));

        jb_CrearCliente.setText("Crear Cliente");
        jb_CrearCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_CrearClienteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_CrearClienteLayout = new javax.swing.GroupLayout(jd_CrearCliente.getContentPane());
        jd_CrearCliente.getContentPane().setLayout(jd_CrearClienteLayout);
        jd_CrearClienteLayout.setHorizontalGroup(
            jd_CrearClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_CrearClienteLayout.createSequentialGroup()
                .addGroup(jd_CrearClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_CrearClienteLayout.createSequentialGroup()
                        .addGap(368, 368, 368)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_CrearClienteLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jd_CrearClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jd_CrearClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(js_Edad, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jd_CrearClienteLayout.createSequentialGroup()
                                .addGroup(jd_CrearClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jd_CrearClienteLayout.createSequentialGroup()
                                        .addComponent(js_Suciedad, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel10))
                                    .addGroup(jd_CrearClienteLayout.createSequentialGroup()
                                        .addComponent(jt_NumPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel8))
                                    .addGroup(jd_CrearClienteLayout.createSequentialGroup()
                                        .addComponent(jt_NombreC, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(117, 117, 117)
                                        .addComponent(jLabel4)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jd_CrearClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jt_Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cb_Size, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(js_NumPuertas, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jd_CrearClienteLayout.createSequentialGroup()
                        .addGap(377, 377, 377)
                        .addComponent(jLabel6))
                    .addGroup(jd_CrearClienteLayout.createSequentialGroup()
                        .addGap(371, 371, 371)
                        .addComponent(jb_CrearCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jd_CrearClienteLayout.setVerticalGroup(
            jd_CrearClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_CrearClienteLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_CrearClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jt_Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt_NombreC, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(30, 30, 30)
                .addGroup(jd_CrearClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(js_Edad, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(jLabel6)
                .addGroup(jd_CrearClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_CrearClienteLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel7))
                    .addGroup(jd_CrearClienteLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jd_CrearClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jt_NumPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(cb_Size, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(44, 44, 44)
                .addGroup(jd_CrearClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(js_Suciedad, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(js_NumPuertas, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jb_CrearCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        jd_CrearEmpleado.setTitle("Crear Empleado");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setText("Crear Empleado");

        jLabel12.setText("Nombre: ");

        jLabel13.setText("Apellido:");

        jLabel14.setText("Edad: ");

        js_EdadE.setModel(new javax.swing.SpinnerNumberModel(18, 18, 100, 1));

        jb_CrearEmpleado.setText("Crear Empleado");
        jb_CrearEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_CrearEmpleadoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_CrearEmpleadoLayout = new javax.swing.GroupLayout(jd_CrearEmpleado.getContentPane());
        jd_CrearEmpleado.getContentPane().setLayout(jd_CrearEmpleadoLayout);
        jd_CrearEmpleadoLayout.setHorizontalGroup(
            jd_CrearEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_CrearEmpleadoLayout.createSequentialGroup()
                .addGroup(jd_CrearEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_CrearEmpleadoLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jd_CrearEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addGroup(jd_CrearEmpleadoLayout.createSequentialGroup()
                                .addGroup(jd_CrearEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jd_CrearEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jd_CrearEmpleadoLayout.createSequentialGroup()
                                        .addComponent(jt_NombreE, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(87, 87, 87)
                                        .addComponent(jLabel13))
                                    .addComponent(js_EdadE, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jt_ApelldioEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_CrearEmpleadoLayout.createSequentialGroup()
                        .addGap(320, 320, 320)
                        .addComponent(jb_CrearEmpleado)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        jd_CrearEmpleadoLayout.setVerticalGroup(
            jd_CrearEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_CrearEmpleadoLayout.createSequentialGroup()
                .addGroup(jd_CrearEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jd_CrearEmpleadoLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(jd_CrearEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jt_ApelldioEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_CrearEmpleadoLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel11)
                        .addGroup(jd_CrearEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_CrearEmpleadoLayout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jLabel12))
                            .addGroup(jd_CrearEmpleadoLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jt_NombreE, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(jd_CrearEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_CrearEmpleadoLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel14))
                    .addGroup(jd_CrearEmpleadoLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(js_EdadE, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(jb_CrearEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel15.setText("Visualizar Clientes");

        jl_Clientes.setModel(new DefaultListModel());
        jl_Clientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_ClientesMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jl_Clientes);

        javax.swing.GroupLayout jd_VisualizarClientesLayout = new javax.swing.GroupLayout(jd_VisualizarClientes.getContentPane());
        jd_VisualizarClientes.getContentPane().setLayout(jd_VisualizarClientesLayout);
        jd_VisualizarClientesLayout.setHorizontalGroup(
            jd_VisualizarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_VisualizarClientesLayout.createSequentialGroup()
                .addGroup(jd_VisualizarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_VisualizarClientesLayout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(jLabel15))
                    .addGroup(jd_VisualizarClientesLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jd_VisualizarClientesLayout.setVerticalGroup(
            jd_VisualizarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_VisualizarClientesLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel15)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        jd_AgregarCarros.setTitle("Asignar Carros a Empleado");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel16.setText("Asignar Carros");

        jb_Asignar.setText("----->");
        jb_Asignar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_AsignarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_AgregarCarrosLayout = new javax.swing.GroupLayout(jd_AgregarCarros.getContentPane());
        jd_AgregarCarros.getContentPane().setLayout(jd_AgregarCarrosLayout);
        jd_AgregarCarrosLayout.setHorizontalGroup(
            jd_AgregarCarrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_AgregarCarrosLayout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addComponent(jLabel16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jd_AgregarCarrosLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(cb_Client, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(jb_Asignar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(cb_Empleados, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );
        jd_AgregarCarrosLayout.setVerticalGroup(
            jd_AgregarCarrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_AgregarCarrosLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel16)
                .addGap(112, 112, 112)
                .addGroup(jd_AgregarCarrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_Client, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_Asignar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_Empleados, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(196, Short.MAX_VALUE))
        );

        jmi_AgregarUnCarro.setText("Agregar un Carro");
        jmi_AgregarUnCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_AgregarUnCarroActionPerformed(evt);
            }
        });
        popup_VC.add(jmi_AgregarUnCarro);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel17.setText("Crea carro a cliente");

        jLabel18.setText("Placa:");

        jLabel19.setText("Size:");

        cb_SizeA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Peque", "Mediano", "Grande", " " }));

        jLabel20.setText("Num Puertas");

        js_NumA.setModel(new javax.swing.SpinnerNumberModel(2, 2, 10, 1));

        jLabel21.setText("Niv Suciedad");

        js_SuciedadA.setModel(new javax.swing.SpinnerNumberModel(5, 5, 10, 1));

        jb_AgregarO.setText("Agregar a Owner");
        jb_AgregarO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_AgregarOMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_AgregarCarroLayout = new javax.swing.GroupLayout(jd_AgregarCarro.getContentPane());
        jd_AgregarCarro.getContentPane().setLayout(jd_AgregarCarroLayout);
        jd_AgregarCarroLayout.setHorizontalGroup(
            jd_AgregarCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_AgregarCarroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(262, 262, 262))
            .addGroup(jd_AgregarCarroLayout.createSequentialGroup()
                .addGroup(jd_AgregarCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_AgregarCarroLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jd_AgregarCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jd_AgregarCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jd_AgregarCarroLayout.createSequentialGroup()
                                .addComponent(jt_PlacaA, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(90, 90, 90)
                                .addComponent(jLabel19))
                            .addGroup(jd_AgregarCarroLayout.createSequentialGroup()
                                .addComponent(js_NumA, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel21))))
                    .addGroup(jd_AgregarCarroLayout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addComponent(jb_AgregarO, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jd_AgregarCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_SizeA, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(js_SuciedadA, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(181, Short.MAX_VALUE))
        );
        jd_AgregarCarroLayout.setVerticalGroup(
            jd_AgregarCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_AgregarCarroLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel17)
                .addGroup(jd_AgregarCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_AgregarCarroLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel18))
                    .addGroup(jd_AgregarCarroLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jd_AgregarCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jt_PlacaA, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)
                            .addComponent(cb_SizeA, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jd_AgregarCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_AgregarCarroLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(jd_AgregarCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(js_NumA, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_AgregarCarroLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(js_SuciedadA, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                .addComponent(jb_AgregarO, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Try Carwash xd");

        jt_Tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Placa", "Size", "Nivel Suciedad", "Tiempo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jt_Tabla1);

        jt_Tabla2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Placa", "Size", "Nivel Suciedad", "Tiempo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jt_Tabla2);

        jt_Tabla3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Placa", "Size", "Nivel Suciedad", "Tiempo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jt_Tabla3);

        jb_IniciarHilos.setText("Iniciar");
        jb_IniciarHilos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_IniciarHilosMouseClicked(evt);
            }
        });

        jm_MenuSuperior.setText("Archivo");

        jmi_CrearCliente.setText("Crear Clientes");
        jmi_CrearCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_CrearClienteActionPerformed(evt);
            }
        });
        jm_MenuSuperior.add(jmi_CrearCliente);

        jmi_CrearEmpleado.setText("Crear Empleado");
        jmi_CrearEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_CrearEmpleadoActionPerformed(evt);
            }
        });
        jm_MenuSuperior.add(jmi_CrearEmpleado);

        jmi_VerClientes.setText("Visualizar Clientes");
        jmi_VerClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_VerClientesActionPerformed(evt);
            }
        });
        jm_MenuSuperior.add(jmi_VerClientes);

        jmi_AsignarCarros.setText("Asignar Carros");
        jmi_AsignarCarros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_AsignarCarrosActionPerformed(evt);
            }
        });
        jm_MenuSuperior.add(jmi_AsignarCarros);

        jmi_GuardarDatos.setText("Guardar Datos");
        jmi_GuardarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_GuardarDatosActionPerformed(evt);
            }
        });
        jm_MenuSuperior.add(jmi_GuardarDatos);

        jmi_SubirData.setText("Subir Datos");
        jmi_SubirData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_SubirDataActionPerformed(evt);
            }
        });
        jm_MenuSuperior.add(jmi_SubirData);

        jMenuBar1.add(jm_MenuSuperior);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cb_Empleado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1)
                            .addComponent(jp_Barra1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2)
                            .addComponent(cb_Empleado2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jp_Barra2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3)
                            .addComponent(cb_Empleado3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jp_Barra3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(585, 585, 585)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(653, 653, 653)
                        .addComponent(jb_IniciarHilos, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jp_Barra3, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jp_Barra1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jp_Barra2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_Empleado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_Empleado2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_Empleado3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                .addComponent(jb_IniciarHilos, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmi_CrearClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_CrearClienteActionPerformed
        jd_CrearCliente.setModal(true);
        jd_CrearCliente.pack();
        jd_CrearCliente.setLocationRelativeTo(this);
        jd_CrearCliente.setVisible(true);
    }//GEN-LAST:event_jmi_CrearClienteActionPerformed

    private void jmi_CrearEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_CrearEmpleadoActionPerformed
        jd_CrearEmpleado.setModal(true);
        jd_CrearEmpleado.pack();
        jd_CrearEmpleado.setLocationRelativeTo(this);
        jd_CrearEmpleado.setVisible(true);
    }//GEN-LAST:event_jmi_CrearEmpleadoActionPerformed

    private void jb_CrearEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_CrearEmpleadoMouseClicked

        if (jt_NombreE.getText().equals("") || jt_ApelldioEmpleado.getText().equals("")) {
            JOptionPane.showMessageDialog(jd_CrearEmpleado, "No puede dejar las casillas vacias!");
        } else {

            Empleado e = new Empleado(
                    jt_NombreE.getText(),
                    jt_ApelldioEmpleado.getText(),
                    (int) js_EdadE.getValue()
            );

            DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_Empleado1.getModel();
            DefaultComboBoxModel modelo2 = (DefaultComboBoxModel) cb_Empleado2.getModel();
            DefaultComboBoxModel modelo3 = (DefaultComboBoxModel) cb_Empleado3.getModel();
            DefaultComboBoxModel modelo4 = (DefaultComboBoxModel) cb_Empleado1.getModel();

            modelo.addElement(e);
            modelo2.addElement(e);
            modelo3.addElement(e);
            modelo4.addElement(e);

            cb_Empleado1.setModel(modelo);
            cb_Empleado2.setModel(modelo2);
            cb_Empleado3.setModel(modelo3);
            cb_Empleados.setModel(modelo4);

            JOptionPane.showMessageDialog(jd_CrearEmpleado, "El empleado se agrego exitosamente");

            jt_NombreE.setText("");
            jt_ApelldioEmpleado.setText("");
            js_EdadE.setValue(20);
        }
    }//GEN-LAST:event_jb_CrearEmpleadoMouseClicked

    private void jb_CrearClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_CrearClienteMouseClicked

        if (jt_NombreC.getText().isEmpty() || jt_Apellido.getText().isEmpty()
                || jt_NumPlaca.getText().isEmpty()) {
            JOptionPane.showMessageDialog(jd_CrearCliente, "No puede dejar las casillas vacias");
        } else {

            Cliente p = new Cliente(
                    jt_NombreC.getText(),
                    jt_Apellido.getText(),
                    (int) js_Edad.getValue()
            );

            Carro c = new Carro(
                    jt_NumPlaca.getText(),
                    (String) cb_Size.getSelectedItem(),
                    (int) js_NumPuertas.getValue(),
                    (int) js_Suciedad.getValue()
            );

            p.getCarrosPropios().add(c);

            DefaultListModel modelo = (DefaultListModel) jl_Clientes.getModel();
            DefaultComboBoxModel modelc = (DefaultComboBoxModel) cb_Client.getModel();
            modelo.addElement(p);
            modelc.addElement(p);
            JOptionPane.showMessageDialog(jd_CrearCliente, "El cliente se creo exitosamente");

            jt_NombreC.setText("");
            jt_Apellido.setText("");
            js_Edad.setValue(20);
            jt_NumPlaca.setText("");
            cb_Size.setSelectedIndex(0);
            js_NumPuertas.setValue(2);
            js_Suciedad.setValue(5);

            //asignarCarros();
        }

    }//GEN-LAST:event_jb_CrearClienteMouseClicked

    private void jmi_VerClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_VerClientesActionPerformed
        jd_VisualizarClientes.setModal(true);
        jd_VisualizarClientes.pack();
        jd_VisualizarClientes.setLocationRelativeTo(this);
        jd_VisualizarClientes.setVisible(true);
    }//GEN-LAST:event_jmi_VerClientesActionPerformed

    private void jb_IniciarHilosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_IniciarHilosMouseClicked
        int in1 = cb_Empleado1.getSelectedIndex();
        int in2 = cb_Empleado2.getSelectedIndex();
        int in3 = cb_Empleado3.getSelectedIndex();

        Empleado e1 = (Empleado) cb_Empleado1.getSelectedItem();
        Empleado e2 = (Empleado) cb_Empleado2.getSelectedItem();
        Empleado e3 = (Empleado) cb_Empleado3.getSelectedItem();

        if (in1 == in2 || in1 == in3 || in2 == in1 || in2 == in3 || in3 == in1 || in3 == in2) {
            JOptionPane.showMessageDialog(this, "Los empleados tienen que ser diferentes!");
        } else if (e1.getCarrosLavar().isEmpty() || e2.getCarrosLavar().isEmpty()
                || e3.getCarrosLavar().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Uno de los empleados no tiene carros por lavar");
        } else {

            h1.setE(e1);
            h1.setLavar(true);

            h2.setE(e2);
            h2.setLavar(true);

            h3.setE(e3);
            h3.setLavar(true);
        }
    }//GEN-LAST:event_jb_IniciarHilosMouseClicked

    private void jb_AsignarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_AsignarMouseClicked
        Empleado e = (Empleado) cb_Empleados.getSelectedItem();
        Cliente c = (Cliente) cb_Client.getSelectedItem();

        for (int i = 0; i < c.getCarrosPropios().size(); i++) {
            Carro car = c.getCarrosPropios().get(i);

            if (e.getCarrosLavar().size() <= 5) {
                e.getCarrosLavar().add(car);
            }
        }

        JOptionPane.showMessageDialog(jd_AgregarCarros, "Se agregaron los carros al empleado");
    }//GEN-LAST:event_jb_AsignarMouseClicked

    private void jl_ClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_ClientesMouseClicked
        if (evt.isMetaDown()) {

            if (jl_Clientes.getSelectedIndex() >= 0) {

                popup_VC.show(jl_Clientes, evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_jl_ClientesMouseClicked

    private void jmi_AgregarUnCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_AgregarUnCarroActionPerformed
        jd_AgregarCarro.setModal(true);
        jd_AgregarCarro.pack();
        jd_AgregarCarro.setLocationRelativeTo(this);
        jd_AgregarCarro.setVisible(true);

    }//GEN-LAST:event_jmi_AgregarUnCarroActionPerformed

    private void jb_AgregarOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_AgregarOMouseClicked

        if (jt_PlacaA.getText().isEmpty()) {
            JOptionPane.showMessageDialog(jd_AgregarCarro, "No puede dejar las casillas vacias!");
        } else {
            DefaultListModel modelo = (DefaultListModel) jl_Clientes.getModel();
            int index = jl_Clientes.getSelectedIndex();

            Carro c = new Carro(
                    jt_PlacaA.getText(),
                    (String) cb_SizeA.getSelectedItem(),
                    (int) js_NumA.getValue(),
                    (int) js_SuciedadA.getValue()
            );

            ((Cliente) modelo.getElementAt(index)).getCarrosPropios().add(c);

            jl_Clientes.setModel(modelo);

            jt_PlacaA.setText("");
            cb_SizeA.setSelectedIndex(0);
            js_NumA.setValue(2);
            js_SuciedadA.setValue(5);

            JOptionPane.showMessageDialog(jd_AgregarCarro, "Se agrego el carro correctamente");
        }
    }//GEN-LAST:event_jb_AgregarOMouseClicked

    private void jmi_GuardarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_GuardarDatosActionPerformed
        GuardarClientes gc = new GuardarClientes(jl_Clientes);

        try {
            gc.escribirClientes();
        } catch (Exception e) {
        }

        GuardarEmpleados ge = new GuardarEmpleados(cb_Empleado1);

        try {
            ge.escribirEmpleados();
        } catch (Exception e) {
        }

    }//GEN-LAST:event_jmi_GuardarDatosActionPerformed

    private void jmi_SubirDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_SubirDataActionPerformed
        
        
        GuardarClientes gc = new GuardarClientes(jl_Clientes);

        try {
            DefaultListModel m = (DefaultListModel)gc.escribirLista().getModel();
            jl_Clientes.setModel(m);
            
        } catch (Exception e) {
        }

        GuardarEmpleados ge = new GuardarEmpleados(cb_Empleado1);

        try {
            DefaultComboBoxModel m1 = (DefaultComboBoxModel)ge.guardarComboBox().getModel();
            cb_Empleado1.setModel(m1);
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jmi_SubirDataActionPerformed

    private void jmi_AsignarCarrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_AsignarCarrosActionPerformed
        jd_AgregarCarro.setModal(true);
        jd_AgregarCarro.pack();
        jd_AgregarCarro.setLocationRelativeTo(this);
        jd_AgregarCarro.setVisible(true);
    }//GEN-LAST:event_jmi_AsignarCarrosActionPerformed

    private void asignarCarros() {
        if (cb_Empleado1.getItemCount() == 0) {
            JOptionPane.showMessageDialog(this, "No hay empleados para asignar carros");
        } else {
            DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_Empleado1.getModel();
            DefaultListModel model2 = (DefaultListModel) jl_Clientes.getModel();
            int c = 0;
            int a = 0;

            for (int i = 0; i < model2.size(); i++) {

                Cliente p;
                p = (Cliente) model2.getElementAt(i);

                Empleado e;
                e = (Empleado) modelo.getElementAt(i);

                while (e.getCarrosLavar().size() < 5 || c < p.getCarrosPropios().size()) {
                    Carro car = p.getCarrosPropios().get(c);

                    e.getCarrosLavar().add(car);

                    p.getCarrosPropios().remove(car);
                    c++;
                }

                c = 0;

                if (a < modelo.getSize()) {
                    a++;
                } else {
                    a = 0;
                }

            }

            cb_Empleado1.setModel(modelo);
            cb_Empleado2.setModel(modelo);
            cb_Empleado3.setModel(modelo);
            jl_Clientes.setModel(model2);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_Client;
    private javax.swing.JComboBox<String> cb_Empleado1;
    private javax.swing.JComboBox<String> cb_Empleado2;
    private javax.swing.JComboBox<String> cb_Empleado3;
    private javax.swing.JComboBox<String> cb_Empleados;
    private javax.swing.JComboBox<String> cb_Size;
    private javax.swing.JComboBox<String> cb_SizeA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton jb_AgregarO;
    private javax.swing.JButton jb_Asignar;
    private javax.swing.JButton jb_CrearCliente;
    private javax.swing.JButton jb_CrearEmpleado;
    private javax.swing.JButton jb_IniciarHilos;
    private javax.swing.JDialog jd_AgregarCarro;
    private javax.swing.JDialog jd_AgregarCarros;
    private javax.swing.JDialog jd_CrearCliente;
    private javax.swing.JDialog jd_CrearEmpleado;
    private javax.swing.JDialog jd_VisualizarClientes;
    private javax.swing.JList<String> jl_Clientes;
    private javax.swing.JMenu jm_MenuSuperior;
    private javax.swing.JMenuItem jmi_AgregarUnCarro;
    private javax.swing.JMenuItem jmi_AsignarCarros;
    private javax.swing.JMenuItem jmi_CrearCliente;
    private javax.swing.JMenuItem jmi_CrearEmpleado;
    private javax.swing.JMenuItem jmi_GuardarDatos;
    private javax.swing.JMenuItem jmi_SubirData;
    private javax.swing.JMenuItem jmi_VerClientes;
    private javax.swing.JProgressBar jp_Barra1;
    private javax.swing.JProgressBar jp_Barra2;
    private javax.swing.JProgressBar jp_Barra3;
    private javax.swing.JSpinner js_Edad;
    private javax.swing.JSpinner js_EdadE;
    private javax.swing.JSpinner js_NumA;
    private javax.swing.JSpinner js_NumPuertas;
    private javax.swing.JSpinner js_Suciedad;
    private javax.swing.JSpinner js_SuciedadA;
    private javax.swing.JTextField jt_ApelldioEmpleado;
    private javax.swing.JTextField jt_Apellido;
    private javax.swing.JTextField jt_NombreC;
    private javax.swing.JTextField jt_NombreE;
    private javax.swing.JTextField jt_NumPlaca;
    private javax.swing.JTextField jt_PlacaA;
    private javax.swing.JTable jt_Tabla1;
    private javax.swing.JTable jt_Tabla2;
    private javax.swing.JTable jt_Tabla3;
    private javax.swing.JPopupMenu popup_VC;
    // End of variables declaration//GEN-END:variables

    //Hilos 
    HiloTabla1 h1;
    HiloTabla2 h2;
    HiloTabla3 h3;

}
